# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02796ad6faa0b16ece8883e3123f55616d036cb41ac3e871c85a635fafb4a736a1687eecb560d0a1d0b27c2b906b6209d2feaca781c1b5f444c6c07f58c04c28

test:
  secret_key_base: 160df617c105af85417f35bf710fd2c278cce6e84328049a2587bef4c1401a773e0518ba33a524d4666ce17ca95d7e25bd87998b54f3fd3b3e7ea15663d861b9

staging:
  secret_key_base: 02796ad6faa0b16ece8883e3123f55616d036cb41ac3e871c85a635fafb4a736a1687eecb560d0a1d0b27c2b906b6209d2feaca781c1b5f444c6c07f58c04c28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
